version: '3'

services:
  app:
    image: wintercitizen/market:application
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=market
      - POSTGRES_USER=postgres
    networks:
      - local
    working_dir: /app/src/
    volumes:
      - media:/app/src/media
    ports:
      - 8080:8080
    entrypoint: ./docker-entrypoint.sh

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=market
    networks:
      - local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # nginx:
  #   image: wintercitizen/market:nginx
  #   networks:
  #     - local
  #   ports:
  #     - 80:80
  #   volumes:
  #     - media:/media

networks:
  local:
volumes:
  postgres_data:
  media:
