version: '3'

services:
  app:
    image: wintercitizen/market:application
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - PORT=8000
    networks:
      - local
    working_dir: /app/src/
    volumes:
      - media:/app/src/media
    command: python main.py

  mongo:
    image: mongo:latest
    networks:
      - local
    volumes:
      - mongo_data:/data/db

  nginx:
    image: wintercitizen/market:nginx
    networks:
      - local
    ports:
      - 8000:80
    volumes:
      - media:/media

networks:
  local:
volumes:
  mongo_data:
  media:
