version: '3'

services:
  doors:
    build: .
    container_name: doors
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - PORT=8000
    networks:
      - local
    working_dir: /app/src/
    ports:
      - 80:8000
    volumes:
      - static:/app/src/static
      - media:/app/src/media
    command: python main.py

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - local
    volumes:
      - mongo_data:/data/db

networks:
  local:
volumes:
  mongo_data:
  static:
  media:
