version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
          name: Build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build --target nginx -t wintercitizen/market:nginx && docker push wintercitizen/market:nginx .
            docker build -t wintercitizen/market:application . && docker push wintercitizen/market:application .
      - run:
          name: Push images
          command: |
              docker push wintercitizen/market:nginx
              docker push wintercitizen/market:application
  deploy:
    docker:
      - image: alpine:latest
    steps:
      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
      - run:
          name: Install openssh
          command: apk update && apk add openssh
      - add_ssh_keys:
          fingerprints:
            - "0c:a5:21:d2:1f:cc:0a:30:bf:b6:f0:37:e2:a1:18:2e"
      - checkout
      - run: echo $HOST_FINGERPRINT >> ~/.ssh/known_hosts
      - run:
          name: Deploy to DigitalOcean & run
          command: |
            scp -r ./docker-compose.yml* $SSH_USER@$SSH_HOST:/app/market/docker-compose.yml
            ssh $SSH_USER@SSH_HOST "cd /app/market && docker-compose pull && docker-compose up -d"


workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master