# Generated by Django 2.2 on 2019-04-06 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('value', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвета',
            },
        ),
        migrations.CreateModel(
            name='CoverMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'отделка',
                'verbose_name_plural': 'отделки',
            },
        ),
        migrations.CreateModel(
            name='FrameMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'каркас полотна',
                'verbose_name_plural': 'каркасы полотна',
            },
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'высота',
                'verbose_name_plural': 'высоты',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.CreateModel(
            name='PackingMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'упаковка',
                'verbose_name_plural': 'упаковки',
            },
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'ширина',
                'verbose_name_plural': 'ширины',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doors.Category')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
                'unique_together': {('title', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('thickness', models.PositiveIntegerField(verbose_name='толщина полотна (мм)')),
                ('price', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='цена')),
                ('cover_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doors.CoverMaterial', verbose_name='отделка')),
                ('frame_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doors.FrameMaterial', verbose_name='каркас полотна')),
                ('heights', models.ManyToManyField(to='doors.Height', verbose_name='высоты')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doors.Manufacturer', verbose_name='производитель')),
                ('packings', models.ManyToManyField(to='doors.PackingMaterial', verbose_name='материалы упаковки')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doors.Subcategory', verbose_name='подкатегория')),
                ('widths', models.ManyToManyField(to='doors.Width', verbose_name='ширины')),
            ],
            options={
                'verbose_name': 'дверь',
                'verbose_name_plural': 'двери',
                'unique_together': {('title', 'manufacturer', 'frame_material', 'cover_material', 'thickness')},
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doors.Color')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.Door')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'unique_together': {('image', 'color'), ('image', 'color', 'door')},
            },
        ),
    ]
