# Generated by Django 2.2 on 2019-04-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_auto_20190407_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='heights',
            field=models.ManyToManyField(blank=True, to='doors.Height', verbose_name='высоты'),
        ),
        migrations.AlterField(
            model_name='door',
            name='packings',
            field=models.ManyToManyField(blank=True, to='doors.PackingMaterial', verbose_name='материалы упаковки'),
        ),
        migrations.AlterField(
            model_name='door',
            name='widths',
            field=models.ManyToManyField(blank=True, to='doors.Width', verbose_name='ширины'),
        ),
    ]
